### PR TITLE
Fix priorityClassName

### PR DESCRIPTION
**Pull request by giskou**
It should be under spec not containers 😅

### CODE REVIEW

**Comment by Zelldon** [comment]
Hey @giskou thanks for fixing it good catch :D could you please also fix it for the gateway?
In your last PR your also added it on the gateway deployment https://github.com/camunda-community-hub/camunda-cloud-helm/issues/67 :)

**Comment by giskou** [comment]
Right, forgot about that.
I'll add it to this PR

**Comment by giskou** [comment]
@Zelldon there you go :)

**Review by Zelldon — APPROVED** [review]
Thanks @giskou  :rocket:

**Pull request merged**
