### PR TITLE
Simplify Helm Charts repo

### PR DESCRIPTION
**Pull request by Zelldon**
1. Removes all charts which have been replaced by ccsm-helm:
   * zeebe-full
   * zeebe-cluster
   * zeebe-operate
   * zeebe-tasklist
2. ~Simplify/rewrite root readme.~ https://github.com/camunda-community-hub/camunda-cloud-helm/pull/180
    - ~Remove old references~
    - ~Rework the architecture image~
    - ~Point to CCSM Helm readme for configuration information~
3. ~Rename tests dir to kind~ Merged via #171 
4. ~Remove old dependencies~ Merged via #172 
    - ~Prometheus controller~
    - ~Kibana~

New Image:

HelmChartImage

### CODE REVIEW

**Comment by npepinpe** [comment]
Should we keep the old charts in an archived repository somewhere for existing users?

**Comment by Zelldon** [comment]
Tbh. I see no reason for it. I don't want and have no time to maintain them. Old releases are still available via https://github.com/camunda-community-hub/camunda-cloud-helm/blob/gh-pages/index.yaml. But open for discussion. 

The zeeqs chart I want to move out as well, but haven't done yet.

**Comment by npepinpe** [comment]
Hm, should we create a new repo for the new charts and archive the old repo? I don't want to maintain the others either, but for visibility purposes they could remain archived.

**Review by Sijoma — APPROVED** [review]
Looks good to me. LGTM. 

Not sure if this would require a new repository. 💭

**Review by menski — APPROVED** [review]
Looks good to me, after thinking more about this I agree that we don't need a separate repository for the old charts. People can retrieve the old charts using the git history and fork the repository if needed. By removing them completely from the repository right now we make it transparent that we don't have an intention to further maintain them

**Pull request merged**
